version: '3.7'

networks:
  default:
    external:
      name: impact-karma

volumes:
  npm-test-modules:
  redis-test-data:
  db-test-data:

services:
  redis-test:
    image: redis:6-alpine
    container_name: redis-test
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-test-data:/data/redis
    restart: unless-stopped

  mongo-test:
    image: mongo
    container_name: mongo-test
    restart: unless-stopped
    volumes:
      - db-test-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  karmawallet-backend-ts-test:
    restart: unless-stopped
    container_name: karmawallet-backend-ts-test
    build:
      context: ./
      dockerfile: ./test.Dockerfile
    env_file:
      - .env
    environment:
      DB_URL: mongo-test:27017
      DB_USER: root
      DB_PASS: example
      REDIS_URL: redis-test
      REDIS_PORT: 6379
    depends_on:
      - redis-test
      - mongo-test
    volumes:
      - .:/kw-backend
      - npm-test-modules:/kw-backend/node_modules
