export enum ActiveCampaignSyncTypes {
  BACKFILL = 'backfill',
  CASHBACK_SIMULATION = 'cashbackSimulation',
  REMOVE_DUPLICATE_CONTACT_AUTOMAITONS = 'removeDuplicateContactAutomations',
  DAILY = 'daily',
  GROUP = 'group',
  INITIAL = 'initial',
  MONTHLY = 'monthly',
  QUARTERLY = 'quarterly',
  SPENDING_ANALYSIS = 'spendingAnalysis',
  WEEKLY = 'weekly',
  YEARLY = 'yearly',
}

export enum ActiveCampaignCustomFields {
  carbonEmissionsMonthly = 'carbonEmissionsMonthly',
  carbonEmissionsYearly = 'carbonEmissionsYearly',
  carbonOffsetDollars = 'carbonOffsetDollars',
  carbonOffsetTonnes = 'carbonOffsetTonnes',
  cashbackDollarsAvailable = 'cashbackDollarsAvailable',
  cashbackDollarsEarnedMonthly = 'cashbackDollarsEarnedMonthly',
  cashbackDollarsEarnedYearly = 'cashbackDollarsEarnedYearly',
  dateJoined = 'dateJoined',
  firstLinkedCardDate = 'firstLinkedCardDate',
  hasLinkedCard = 'hasLinkedCard',
  hasLinkedPaypal = 'hasLinkedPaypal',
  impactnegative = 'impactnegative',
  impactneutral = 'impactneutral',
  impactpositive = 'impactpositive',
  karmaScoreYearly = 'karmaScoreYearly',
  lastLinkedCardDate = 'lastLinkedCardDate',
  lastLogin = 'lastLogin',
  loginCountLastMonth = 'loginCountLastMonth',
  loginCountLastWeek = 'loginCountLastWeek',
  loginCountLastYear = 'loginCountLastYear',
  loginCountTotal = 'loginCountTotal',
  madeCashbackEligiblePurchase = 'madeCashbackEligiblePurchase',
  missedCashbackDollarsLastMonth = 'missedCashbackDollarsLastMonth',
  missedCashbackTransactionNumberLastMonth = 'missedCashbackTransactionNumberLastMonth',
  monthsKarmaScore = 'monthsKarmaScore',
  negativePurchaseDollarsLastThirtyDays = 'negativePurchaseDollarsLastThirtyDays',
  numLinkedCards = 'numLinkedCards',
  numNegativePurchasesLastThirtyDays = 'numNegativePurchasesLastThirtyDays',
  numPositivePurchasesLastThirtyDays = 'numPositivePurchasesLastThirtyDays',
  positivePurchaseDollarsLastThirtyDays = 'positivePurchaseDollarsLastThirtyDays',
  userId = 'userId',
}
