export const StateAbbreviationEnum = {
  AE: 'AE',
  AA: 'AA',
  AP: 'AP',
  AL: 'AL',
  AK: 'AK',
  AS: 'AS',
  AZ: 'AZ',
  AR: 'AR',
  CA: 'CA',
  CO: 'CO',
  CT: 'CT',
  DE: 'DE',
  DC: 'DC',
  FM: 'FM',
  FL: 'FL',
  GA: 'GA',
  GU: 'GU',
  HI: 'HI',
  ID: 'ID',
  IL: 'IL',
  IN: 'IN',
  IA: 'IA',
  KS: 'KS',
  KY: 'KY',
  LA: 'LA',
  ME: 'ME',
  MH: 'MH',
  MD: 'MD',
  MA: 'MA',
  MI: 'MI',
  MN: 'MN',
  MS: 'MS',
  MO: 'MO',
  MT: 'MT',
  NE: 'NE',
  NV: 'NV',
  NH: 'NH',
  NJ: 'NJ',
  NM: 'NM',
  NY: 'NY',
  NC: 'NC',
  ND: 'ND',
  MP: 'MP',
  OH: 'OH',
  OK: 'OK',
  OR: 'OR',
  PW: 'PW',
  PA: 'PA',
  PR: 'PR',
  RI: 'RI',
  SC: 'SC',
  SD: 'SD',
  TN: 'TN',
  TX: 'TX',
  UT: 'UT',
  VT: 'VT',
  VI: 'VI',
  VA: 'VA',
  WA: 'WA',
  WV: 'WV',
  WI: 'WI',
  WY: 'WY',
} as const;
export type StateAbbreviationEnumValues = (typeof StateAbbreviationEnum)[keyof typeof StateAbbreviationEnum];

export const StateNameEnum = {
  ArmedForces: 'Armed Forces',
  ArmedForcesAmericas: 'Armed Forces Americas',
  ArmedForcesPacific: 'Armed Forces Pacific',
  Alabama: 'Alabama',
  Alaska: 'Alaska',
  AmericanSamoa: 'American Samoa',
  Arizona: 'Arizona',
  Arkansas: 'Arkansas',
  California: 'California',
  Colorado: 'Colorado',
  Connecticut: 'Connecticut',
  Delaware: 'Delaware',
  DistrictOfColumbia: 'District Of Columbia',
  Florida: 'Florida',
  Georgia: 'Georgia',
  Guam: 'Guam',
  Hawaii: 'Hawaii',
  Idaho: 'Idaho',
  Illinois: 'Illinois',
  Indiana: 'Indiana',
  Iowa: 'Iowa',
  Kansas: 'Kansas',
  Kentucky: 'Kentucky',
  Louisiana: 'Louisiana',
  Maine: 'Maine',
  Maryland: 'Maryland',
  Massachusetts: 'Massachusetts',
  Michigan: 'Michigan',
  Minnesota: 'Minnesota',
  Mississippi: 'Mississippi',
  Missouri: 'Missouri',
  Montana: 'Montana',
  NorthCarolina: 'North Carolina',
  NorthDakota: 'North Dakota',
  Nebraska: 'Nebraska',
  Nevada: 'Nevada',
  NewHampshire: 'New Hampshire',
  NewJersey: 'New Jersey',
  NewMexico: 'New Mexico',
  NewYork: 'New York',
  Ohio: 'Ohio',
  Oklahoma: 'Oklahoma',
  Oregon: 'Oregon',
  Pennsylvania: 'Pennsylvania',
  PuertoRico: 'Puerto Rico',
  RhodeIsland: 'Rhode Island',
  SouthCarolina: 'South Carolina',
  SouthDakota: 'South Dakota',
  Tennessee: 'Tennessee',
  Texas: 'Texas',
  Utah: 'Utah',
  Vermont: 'Vermont',
  Virginia: 'Virginia',
  VirginIslands: 'Virgin Islands',
  WashingtonDC: 'Washington DC',
  Washington: 'Washington',
  WestVirginia: 'West Virginia',
  Wisconsin: 'Wisconsin',
  Wyoming: 'Wyoming',
} as const;
export type StateNameEnumValues = (typeof StateNameEnum)[keyof typeof StateNameEnum];

export const ZipCodeRangesForStates = [
  { zipStart: 35000, zipEnd: 36999, code: StateAbbreviationEnum.AL, long: StateNameEnum.Alabama },
  { zipStart: 99500, zipEnd: 99999, code: StateAbbreviationEnum.AK, long: StateNameEnum.Alaska },
  { zipStart: 85000, zipEnd: 86999, code: StateAbbreviationEnum.AZ, long: StateNameEnum.Arizona },
  { zipStart: 71600, zipEnd: 72999, code: StateAbbreviationEnum.AR, long: StateNameEnum.Arkansas },
  { zipStart: 90000, zipEnd: 96699, code: StateAbbreviationEnum.CA, long: StateNameEnum.California },
  { zipStart: 80000, zipEnd: 81999, code: StateAbbreviationEnum.CO, long: StateNameEnum.Colorado },
  { zipStart: 6000, zipEnd: 6999, code: StateAbbreviationEnum.CT, long: StateNameEnum.Connecticut },
  { zipStart: 19700, zipEnd: 19999, code: StateAbbreviationEnum.DE, long: StateNameEnum.Delaware },
  { zipStart: 32000, zipEnd: 34999, code: StateAbbreviationEnum.FL, long: StateNameEnum.Florida },
  { zipStart: 30000, zipEnd: 31999, code: StateAbbreviationEnum.GA, long: StateNameEnum.Georgia },
  { zipStart: 96700, zipEnd: 96999, code: StateAbbreviationEnum.HI, long: StateNameEnum.Hawaii },
  { zipStart: 83200, zipEnd: 83999, code: StateAbbreviationEnum.ID, long: StateNameEnum.Idaho },
  { zipStart: 60000, zipEnd: 62999, code: StateAbbreviationEnum.IL, long: StateNameEnum.Illinois },
  { zipStart: 46000, zipEnd: 47999, code: StateAbbreviationEnum.IN, long: StateNameEnum.Indiana },
  { zipStart: 50000, zipEnd: 52999, code: StateAbbreviationEnum.IA, long: StateNameEnum.Iowa },
  { zipStart: 66000, zipEnd: 67999, code: StateAbbreviationEnum.KS, long: StateNameEnum.Kansas },
  { zipStart: 40000, zipEnd: 42999, code: StateAbbreviationEnum.KY, long: StateNameEnum.Kentucky },
  { zipStart: 70000, zipEnd: 71599, code: StateAbbreviationEnum.LA, long: StateNameEnum.Louisiana },
  { zipStart: 3900, zipEnd: 4999, code: StateAbbreviationEnum.ME, long: StateNameEnum.Maine },
  { zipStart: 20600, zipEnd: 21999, code: StateAbbreviationEnum.MD, long: StateNameEnum.Maryland },
  { zipStart: 1000, zipEnd: 2799, code: StateAbbreviationEnum.MA, long: StateNameEnum.Massachusetts },
  { zipStart: 48000, zipEnd: 49999, code: StateAbbreviationEnum.MI, long: StateNameEnum.Michigan },
  { zipStart: 55000, zipEnd: 56999, code: StateAbbreviationEnum.MN, long: StateNameEnum.Minnesota },
  { zipStart: 38600, zipEnd: 39999, code: StateAbbreviationEnum.MS, long: StateNameEnum.Mississippi },
  { zipStart: 63000, zipEnd: 65999, code: StateAbbreviationEnum.MO, long: StateNameEnum.Missouri },
  { zipStart: 59000, zipEnd: 59999, code: StateAbbreviationEnum.MT, long: StateNameEnum.Montana },
  { zipStart: 27000, zipEnd: 28999, code: StateAbbreviationEnum.NC, long: StateNameEnum.NorthCarolina },
  { zipStart: 58000, zipEnd: 58999, code: StateAbbreviationEnum.ND, long: StateNameEnum.NorthDakota },
  { zipStart: 68000, zipEnd: 69999, code: StateAbbreviationEnum.NE, long: StateNameEnum.Nebraska },
  { zipStart: 88900, zipEnd: 89999, code: StateAbbreviationEnum.NV, long: StateNameEnum.Nevada },
  { zipStart: 3000, zipEnd: 3899, code: StateAbbreviationEnum.NH, long: StateNameEnum.NewHampshire },
  { zipStart: 7000, zipEnd: 8999, code: StateAbbreviationEnum.NJ, long: StateNameEnum.NewJersey },
  { zipStart: 87000, zipEnd: 88499, code: StateAbbreviationEnum.NM, long: StateNameEnum.NewMexico },
  { zipStart: 10000, zipEnd: 14999, code: StateAbbreviationEnum.NY, long: StateNameEnum.NewYork },
  { zipStart: 43000, zipEnd: 45999, code: StateAbbreviationEnum.OH, long: StateNameEnum.Ohio },
  { zipStart: 73000, zipEnd: 74999, code: StateAbbreviationEnum.OK, long: StateNameEnum.Oklahoma },
  { zipStart: 97000, zipEnd: 97999, code: StateAbbreviationEnum.OR, long: StateNameEnum.Oregon },
  { zipStart: 15000, zipEnd: 19699, code: StateAbbreviationEnum.PA, long: StateNameEnum.Pennsylvania },
  { zipStart: 300, zipEnd: 999, code: StateAbbreviationEnum.PR, long: StateNameEnum.PuertoRico },
  { zipStart: 2800, zipEnd: 2999, code: StateAbbreviationEnum.RI, long: StateNameEnum.RhodeIsland },
  { zipStart: 29000, zipEnd: 29999, code: StateAbbreviationEnum.SC, long: StateNameEnum.SouthCarolina },
  { zipStart: 57000, zipEnd: 57999, code: StateAbbreviationEnum.SD, long: StateNameEnum.SouthDakota },
  { zipStart: 37000, zipEnd: 38599, code: StateAbbreviationEnum.TN, long: StateNameEnum.Tennessee },
  { zipStart: 75000, zipEnd: 79999, code: StateAbbreviationEnum.TX, long: StateNameEnum.Texas },
  { zipStart: 88500, zipEnd: 88599, code: StateAbbreviationEnum.TX, long: StateNameEnum.Texas },
  { zipStart: 84000, zipEnd: 84999, code: StateAbbreviationEnum.UT, long: StateNameEnum.Utah },
  { zipStart: 5000, zipEnd: 5999, code: StateAbbreviationEnum.VT, long: StateNameEnum.Vermont },
  { zipStart: 22000, zipEnd: 24699, code: StateAbbreviationEnum.VA, long: StateNameEnum.Virginia },
  { zipStart: 20000, zipEnd: 20599, code: StateAbbreviationEnum.DC, long: StateNameEnum.WashingtonDC },
  { zipStart: 98000, zipEnd: 99499, code: StateAbbreviationEnum.WA, long: StateNameEnum.Washington },
  { zipStart: 24700, zipEnd: 26999, code: StateAbbreviationEnum.WV, long: StateNameEnum.WestVirginia },
  { zipStart: 53000, zipEnd: 54999, code: StateAbbreviationEnum.WI, long: StateNameEnum.Wisconsin },
  { zipStart: 82000, zipEnd: 83199, code: StateAbbreviationEnum.WY, long: StateNameEnum.Wyoming },
] as const;

export const states = [
  {
    name: StateNameEnum.ArmedForces,
    abbreviation: StateAbbreviationEnum.AE,
  },
  {
    name: StateNameEnum.ArmedForcesAmericas,
    abbreviation: StateAbbreviationEnum.AA,
  },
  {
    name: StateNameEnum.ArmedForcesPacific,
    abbreviation: StateAbbreviationEnum.AP,
  },
  {
    name: StateNameEnum.Alabama,
    abbreviation: StateAbbreviationEnum.AL,
  },
  {
    name: StateNameEnum.Alaska,
    abbreviation: StateAbbreviationEnum.AK,
  },
  {
    name: StateNameEnum.AmericanSamoa,
    abbreviation: StateAbbreviationEnum.AS,
  },
  {
    name: StateNameEnum.Arizona,
    abbreviation: StateAbbreviationEnum.AZ,
  },
  {
    name: StateNameEnum.Arkansas,
    abbreviation: StateAbbreviationEnum.AR,
  },
  {
    name: StateNameEnum.California,
    abbreviation: StateAbbreviationEnum.CA,
  },
  {
    name: StateNameEnum.Colorado,
    abbreviation: StateAbbreviationEnum.CO,
  },
  {
    name: StateNameEnum.Connecticut,
    abbreviation: StateAbbreviationEnum.CT,
  },
  {
    name: StateNameEnum.Delaware,
    abbreviation: StateAbbreviationEnum.DE,
  },
  {
    name: StateNameEnum.DistrictOfColumbia,
    abbreviation: StateAbbreviationEnum.DC,
  },
  {
    name: StateNameEnum.WashingtonDC,
    abbreviation: StateAbbreviationEnum.DC,
  },
  {
    name: StateNameEnum.Florida,
    abbreviation: StateAbbreviationEnum.FL,
  },
  {
    name: StateNameEnum.Georgia,
    abbreviation: StateAbbreviationEnum.GA,
  },
  {
    name: StateNameEnum.Guam,
    abbreviation: StateAbbreviationEnum.GU,
  },
  {
    name: StateNameEnum.Hawaii,
    abbreviation: StateAbbreviationEnum.HI,
  },
  {
    name: StateNameEnum.Idaho,
    abbreviation: StateAbbreviationEnum.ID,
  },
  {
    name: StateNameEnum.Illinois,
    abbreviation: StateAbbreviationEnum.IL,
  },
  {
    name: StateNameEnum.Indiana,
    abbreviation: StateAbbreviationEnum.IN,
  },
  {
    name: StateNameEnum.Iowa,
    abbreviation: StateAbbreviationEnum.IA,
  },
  {
    name: StateNameEnum.Kansas,
    abbreviation: StateAbbreviationEnum.KS,
  },
  {
    name: StateNameEnum.Kentucky,
    abbreviation: StateAbbreviationEnum.KY,
  },
  {
    name: StateNameEnum.Louisiana,
    abbreviation: StateAbbreviationEnum.LA,
  },
  {
    name: StateNameEnum.Maine,
    abbreviation: StateAbbreviationEnum.ME,
  },
  {
    name: StateNameEnum.Maryland,
    abbreviation: StateAbbreviationEnum.MD,
  },
  {
    name: StateNameEnum.Massachusetts,
    abbreviation: StateAbbreviationEnum.MA,
  },
  {
    name: StateNameEnum.Michigan,
    abbreviation: StateAbbreviationEnum.MI,
  },
  {
    name: StateNameEnum.Minnesota,
    abbreviation: StateAbbreviationEnum.MN,
  },
  {
    name: StateNameEnum.Mississippi,
    abbreviation: StateAbbreviationEnum.MS,
  },
  {
    name: StateNameEnum.Missouri,
    abbreviation: StateAbbreviationEnum.MO,
  },
  {
    name: StateNameEnum.Montana,
    abbreviation: StateAbbreviationEnum.MT,
  },
  {
    name: StateNameEnum.Nebraska,
    abbreviation: StateAbbreviationEnum.NE,
  },
  {
    name: StateNameEnum.Nevada,
    abbreviation: StateAbbreviationEnum.NV,
  },
  {
    name: StateNameEnum.NewHampshire,
    abbreviation: StateAbbreviationEnum.NH,
  },
  {
    name: StateNameEnum.NewJersey,
    abbreviation: StateAbbreviationEnum.NJ,
  },
  {
    name: StateNameEnum.NewMexico,
    abbreviation: StateAbbreviationEnum.NM,
  },
  {
    name: StateNameEnum.NewYork,
    abbreviation: StateAbbreviationEnum.NY,
  },
  {
    name: StateNameEnum.NorthCarolina,
    abbreviation: StateAbbreviationEnum.NC,
  },
  {
    name: StateNameEnum.NorthDakota,
    abbreviation: StateAbbreviationEnum.ND,
  },
  {
    name: StateNameEnum.Ohio,
    abbreviation: StateAbbreviationEnum.OH,
  },
  {
    name: StateNameEnum.Oklahoma,
    abbreviation: StateAbbreviationEnum.OK,
  },
  {
    name: StateNameEnum.Oregon,
    abbreviation: StateAbbreviationEnum.OR,
  },
  {
    name: StateNameEnum.Pennsylvania,
    abbreviation: StateAbbreviationEnum.PA,
  },
  {
    name: StateNameEnum.PuertoRico,
    abbreviation: StateAbbreviationEnum.PR,
  },
  {
    name: StateNameEnum.RhodeIsland,
    abbreviation: StateAbbreviationEnum.RI,
  },
  {
    name: StateNameEnum.SouthCarolina,
    abbreviation: StateAbbreviationEnum.SC,
  },
  {
    name: StateNameEnum.SouthDakota,
    abbreviation: StateAbbreviationEnum.SD,
  },
  {
    name: StateNameEnum.Tennessee,
    abbreviation: StateAbbreviationEnum.TN,
  },
  {
    name: StateNameEnum.Texas,
    abbreviation: StateAbbreviationEnum.TX,
  },
  {
    name: StateNameEnum.Utah,
    abbreviation: StateAbbreviationEnum.UT,
  },
  {
    name: StateNameEnum.Vermont,
    abbreviation: StateAbbreviationEnum.VT,
  },
  {
    name: StateNameEnum.VirginIslands,
    abbreviation: StateAbbreviationEnum.VI,
  },
  {
    name: StateNameEnum.Virginia,
    abbreviation: StateAbbreviationEnum.VA,
  },
  {
    name: StateNameEnum.Washington,
    abbreviation: StateAbbreviationEnum.WA,
  },
  {
    name: StateNameEnum.WestVirginia,
    abbreviation: StateAbbreviationEnum.WV,
  },
  {
    name: StateNameEnum.Wisconsin,
    abbreviation: StateAbbreviationEnum.WI,
  },
  {
    name: StateNameEnum.Wyoming,
    abbreviation: StateAbbreviationEnum.WY,
  },
];
