export const NACHAACHReturnCodesEnum = {
  R01: 'Insufficient Funds',
  R02: 'Account Closed',
  R03: 'No Account/Unable to Locate Account',
  R04: 'Invalid Account Number',
  R05: 'Improper Debit to Consumer Account',
  R06: 'Returned per ODFI Request',
  R07: 'Authorization Revoked by Customer',
  R08: 'Payment Stopped',
  R09: 'Uncollected Funds',
  R10: 'Customer Advises Originator is Not Known to Receiver and/or Originator is Not Authorized by Receiver to Debit Receiver’s Account',
  R11: 'Customer Advises Entry Not in Accordance with the Terms of the Authorization',
  R12: 'Branch Sold to Another DFI',
  R13: 'RDFI Not Qualified to Participate',
  R14: 'Representative Payee Deceased or Unable to Continue in that Capacity',
  R15: 'Beneficiary or Account Holder Deceased',
  R16: 'Bank Account Frozen',
  R17: 'File Record Edit Criteria',
  R18: 'Improper Effective Entry Date',
  R19: 'Amount Field Error',
  R20: 'Non-Transaction Account',
  R21: 'Invalid Company Identification',
  R22: 'Invalid Individual ID Number',
  R23: 'Credit Entry Refused by Receiver',
  R24: 'Duplicate Entry',
  R25: 'Addenda Error',
  R26: 'Mandatory Field Error',
  R27: 'Trace Number Error',
  R28: 'Routing Number Check Digit Error',
  R29: 'Corporate Customer Advises Not Authorized',
  R30: 'RDFI Not Participant in Check Truncation Program',
  R31: 'Permissible Return Entry',
  R32: 'RDFI Non-Settlement',
  R33: 'Return of XCK Entry',
  R34: 'Limited Participation DFI',
  R35: 'Return of Improper Debit Entry',
  R36: 'Return of Improper Credit Entry',
  R37: 'Source Document Presented for Payment',
  R38: 'Stop Payment on Source Document',
  R39: 'Improper Source Document',
} as const;
export type NACHAACHReturnCodeEnumValues = (typeof NACHAACHReturnCodesEnum)[keyof typeof NACHAACHReturnCodesEnum];
