import { Document, model, ObjectId, PaginateModel, Schema } from 'mongoose';
import mongoosePaginate from 'mongoose-paginate-v2';
import { IComplyAdvantageIntegration } from '../integrations/complyAdvantage/types';
import { IMarqetaKycState, IMarqetaUserStatus } from '../integrations/marqeta/types';
import { UserRoles } from '../lib/constants';
import { getUtcDate } from '../lib/date';
import { IModel, IRef } from '../types/model';
import { IArticle } from './article';
import { IPromo, IPromoDocument } from './promo';
import { ComplyAdvantageIntegrationSchema } from './types';

export enum UserEmailStatus {
  Unverified = 'unverified',
  Verified = 'verified',
  Bounced = 'bounced',
  Complained = 'complained',
}

interface IMarqetaIdentification {
  type: string,
  value: string,
}

// TODO: remove alt emails after mapping
export interface IAltEmail {
  email: string;
  status: UserEmailStatus;
}

export interface IEmail {
  email: string;
  status: UserEmailStatus;
  primary: boolean;
  bouncedDate?: Date;
}

export interface IRareUserIntegration {
  userId?: string;
}

export interface IShareASale {
  trackingId?: string;
}

export interface IActiveCampaignUserIntegration {
  userId: string;
  latestSync: Date;
}

export interface IUrlParam {
  key: string;
  value: string;
}

export interface IPaypalUserIntegration {
  user_id: string;
  sub: string;
  name: string;
  middle_name: string;
  email: string;
  verified: Boolean;
  payerId: string;
  verified_account: Boolean;
  email_verified: Boolean;
}

export interface IReferrals {
  params: IUrlParam[];
}

export interface IBiometrics {
  _id?: string;
  biometricKey: string;
  isBiometricEnabled: Boolean;
}

export interface IMarqetaKycResult {
  status: IMarqetaKycState;
  codes: string[];
}

export interface IMarqetaUserIntegrations {
  userToken: string;
  email?: string;
  kycResult?: IMarqetaKycResult;
  first_name?: string;
  last_name?: string;
  birth_date?: string;
  phone?: string;
  address1?: string;
  address2?: string;
  city?: string;
  state?: string;
  country?: string;
  postal_code?: string;
  account_holder_group_token?: string;
  identifications?: IMarqetaIdentification[];
  status?: IMarqetaUserStatus;
  created_time?: string;
  _id?: string;
  reason? :string;
  reason_code? :string;
}

export interface IFCMTokenIntegration {
  token: string;
  deviceId: string;
}

export interface IUserIntegrations {
  rare?: IRareUserIntegration;
  paypal?: IPaypalUserIntegration;
  activecampaign?: IActiveCampaignUserIntegration;
  shareasale?: IShareASale;
  referrals?: IReferrals;
  promos?: IRef<ObjectId, IPromo | IPromoDocument>[];
  biometrics?: IBiometrics[];
  marqeta?: IMarqetaUserIntegrations;
  fcm?: IFCMTokenIntegration[];
  complyAdvantage?: IComplyAdvantageIntegration;
}

export interface IShareableUser {
  email: string;
  name: string;
  dateJoined: Date;
  zipcode: string;
  role: string; // cannot mark as UserRoles due to how mongoose treats enums
  legacyId: string;
}

export interface IDeviceInfo {
  manufacturer: string;
  bundleId: string;
  deviceId: string;
  apiLevel: string;
  applicaitonName: string;
  model: string;
  buildNumber: string;
}

export interface IUser extends IShareableUser {
  emails: IEmail[];
  // TODO: remove alt emails after mapping
  altEmails: IAltEmail[];
  password: string;
  lastModified: Date;
  integrations?: IUserIntegrations;
  isTestIdentity?: boolean;
  isAutoGeneratedPassword?: boolean;
  articles?: {
    queued?: {
      date: Date;
      article: IRef<ObjectId, IArticle>;
    }[];
  };
  deviceInfo?:IDeviceInfo[]
}

export interface IUserDocument extends IUser, Document { }
export type IUserModel = IModel<IUser>;

const userSchema = new Schema({
  emails: [
    {
      type: {
        email: { type: String },
        status: {
          type: String,
          enum: Object.values(UserEmailStatus),
          default: UserEmailStatus.Verified,
        },
        bouncedDate: { type: Date },
        primary: { type: Boolean, default: false },
      },
    },
  ],
  name: { type: String, required: true },
  password: { type: String, required: true },
  dateJoined: { type: Date, default: () => getUtcDate() },
  zipcode: { type: String },
  isTestIdentity: { type: Boolean },
  isAutoGeneratedPassword: { type: Boolean },
  role: {
    type: String,
    default: 'none',
    enum: Object.values(UserRoles),
  },
  lastModified: { type: Date, default: () => getUtcDate() },
  legacyId: { type: String },
  articles: {
    type: {
      queued: [
        {
          type: {
            date: { type: Date, required: true },
            article: { type: Schema.Types.ObjectId, ref: 'article', required: true },
          },
        },
      ],
    },
  },
  integrations: {
    marqeta: {
      type: {
        userToken: { type: String },
        email: { type: String },
        kycResult: {
          status: { type: String },
          codes: { type: Array },
        },
        first_name: { type: String },
        last_name: { type: String },
        birth_date: { type: String },
        phone: { type: String },
        address1: { type: String },
        address2: { type: String },
        city: { type: String },
        state: { type: String },
        country: { type: String },
        postal_code: { type: String },
        reason: { type: String },
        reason_code: { type: String },
        account_holder_group_token: { type: String },
        identifications: [
          {
            type: { type: String },
            value: { type: String },
          },
        ],
        status: { type: String },
        created_time: { type: String },
      },
    },
    rare: {
      type: {
        userId: { type: String },
      },
    },
    paypal: {
      type: {
        payerId: { type: String },
        email: { type: String },
        user_id: { type: String },
        sub: { type: String },
        name: { type: String },
        middle_name: { type: String },
        verified: { type: Boolean },
        verified_account: { type: Boolean },
        email_verified: { type: Boolean },
      },
    },
    activecampaign: {
      type: {
        latestSyncDate: { type: Date },
      },
    },
    shareasale: {
      type: {
        trackingId: { type: String },
      },
    },
    referrals: {
      type: {
        params: { type: Array },
      },
    },
    promos: {
      type: [{ type: Schema.Types.ObjectId, ref: 'promo' }],
    },
    biometrics: [
      {
        type: {
          biometricKey: { type: String },
          isBiometricEnabled: { type: Boolean },
          dateKeyCreated: { type: Date, default: () => getUtcDate() },
        },
      },
    ],
    fcm: [{ token: String, deviceId: String }],
    complyAdvantage: ComplyAdvantageIntegrationSchema,
  },
  deviceInfo: [{
    manufacturer: { type: String },
    bundleId: { type: String },
    deviceId: { type: String },
    apiLevel: { type: String },
    applicaitonName: { type: String },
    model: { type: String },
    buildNumber: { type: String },
  }],
});
userSchema.plugin(mongoosePaginate);

export const UserModel = model<IUserDocument, PaginateModel<IUser>>('user', userSchema);
