#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "${BOLD} Running npm build... ${NORMAL}"
# fi
REDBOLD='\033[0;31;1m'
GREENBOLD='\033[0;32;1m'
BOLD='\033[1m'
NORMAL='\033[0m'

# If there are whitespace errors, print the offending file names and fail.
# exec git diff-index --check --cached $against --

npm run build

if [ $? = 0 ]; then
  echo "${GREENBOLD} Code passed TypeScript  compilation. ✔️\nReady to commit!${NORMAL}"
else
  echo "${REDBOLD} TypeScript  compilation failed. ❌ ${NORMAL}"
  exit 1
fi
